#!/bin/bash
#echo "Checking the solution of the challenge"
#echo "DIAG: instruqt challenge not ready, please check later"
#exit 1

#if [ -f "${USERFILE}" ]
#then
# 	echo "${USERFILE} found."
#else
#   echo "DIAG: ${USERFILE} not found. Please read instructions."
#	exit 1
#fi
