#!/bin/bash
echo "Checking the solution of the challenge"
diff /tmp/all-hosts.lst ~/chal-01-output-wanted.txt 1>/dev/null  || ( echo "De inventory is niet juist gevuld" ; exit 1)  && echo "de inventory ziet er goed uit"
